serverConfigs:
 httpPort : 8081
 httpsPort : 9443
 adminPort : 9463
 readTimeOut : 20
 writeTimeOut : 20
 certificateFile : '../resources/security/server.pem'
 keyFile : '../resources/security/server.key'
 logsDirectory : logs
 enableAccessLogs : true

redisConfigs:
 serverUrl : localhost
 serverPort : 6379
 password : root
 db : 0

dbConfigs:
 -
  name : dashboard
  dialect : mysql
  username : root
  password : root
  dbname : dashboard
  address : localhost:3306
  parameters :
-
  name : portal
  dialect : mysql
  username : root
  password : root
  dbname : portal
  address : localhost:3306
  parameters :

